### ISSUE TITLE
index collection

### ISSUE THREAD

**Issue by psyduck113** [dontbesatisfied/MongoDB-QnA#4]
**Enviroment(please complete the following information):**
 - OS: window
 - Driver :pycharm
 - DB Version [e.g. 4.4]

**Describe the question**

> for(i=0;i<1000000;i++){ db.users.insert( { "i":i, "username":"user"+1, "age":Math.floor(Math,random()*120), "create
d":new Date() } ); }
uncaught exception: ReferenceError: random is not defined :
@(shell):1:72

**Expected behavior**

**Screenshots**

**Comment by dontbesatisfied** [comment]
this is typo error

Math,random -> Math.random
