### ISSUE TITLE
몽고디비에서 무한 스크롤을 구현하는 방법

### ISSUE THREAD

**Issue by onezerokang** [dontbesatisfied/MongoDB-QnA#6]
- OS: [window 10]
 - Driver [mongoose]
 - DB Version [4.4.2]

**Describe the question**
몽고디비에서 무한 스크롤을 구현하려면 어떻게 쿼리를 해야 하는가?

**Expected behavior**
무한 스크롤의 경우 _id값 또는 sorting 필드를 기준으로 쿼리에 lte 조건을 달아서 처리하면 좋다.
find({_id:{$lte:xxxxxxxx}, 원하는쿼리}).sort({_id: -1})

**Comment by SHwan93** [comment]
답변
무한 스크롤의 경우 _id값 또는 sorting 필드를 기준으로 쿼리에 lte 조건을 달아서 처리하면 좋다.
find({_id:{$lte:xxxxxxxx}, 원하는쿼리}).sort({_id: -1})
